name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  cached_network_image: ^3.4.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_typeahead: ^5.2.0
  page_transition: ^2.1.0
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: assets/muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
        - asset: assets/fonts/Muli-Regular.ttf
        - asset: assets/fonts/Muli-SemiBold.ttf
